# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  maven-build: inclasstoday/maven-build@X.Y.Z
workflows:
  version: 2.1
  verify_and_build:
    jobs:
      - maven-build/docker_build:
          context: maven-build
